CFLAGS=-Werror -Wall -g -std=c99 -lm -lblas -lgsl
all: ex1 ex3 ex5 ex6 ex8 ex10 ex11 ex12 ex13 ex14 poly-roots test test-two type-pun byte-repr sizes
clean:
	rm -f ex1 ex3 ex5 ex6 ex8 ex10 ex11 ex12 ex13 ex14 poly-roots test test-two type-pun byte-repr sizes *~
