#
# Makefile for widget examples
#
SHELL=/bin/sh

all: libXs chapter2 chapter4 chapter6 chapter8 chapter3 chapter5 \
     chapter7 chapter9 chapter10 chapter11 chapter12 chapter13 chapter14 
	

libXs: 
	cd lib; make ; cd ..

chapter2: libXs
	cd  ch2; make; cd ..
chapter4: libXs
	cd  ch4; make; cd ..
chapter6: libXs
	cd  ch6; make; cd ..
chapter8: libXs
	cd  ch8; make; cd ..
chapter3: libXs
	cd  ch3; make ; cd ..
chapter5: libXs
	cd  ch5; make ; cd ..
chapter7: libXs
	cd  ch7; make ; cd ..
chapter9: libXs
	cd  ch9; make ; cd ..
chapter10: libXs
	cd  ch10; make; cd ..
chapter11: libXs
	cd  ch11; make; cd ..
chapter12: libXs
	cd  ch12; make; cd ..
chapter13: libXs
	cd  ch13; make; cd ..
chapter14: libXs
	cd  ch14; make; cd ..
 
